title: Clara Michelle
description: "Relatos sobre o trabalho de Clara Michelle e sua equipe."
baseurl: ""
url: "https://michelle.souox.com"
github_username: michelleox

permalink: /p/:slug.html
gtag: G-TZBPFV014K
favicon: "favicon.ico"

# Build settings

theme_config:
  appearance: "back"
  back_home_text: "← light" # customize text for homepage link in post layout
  date_format: "%Y-%m" # customize how date is formatted in post list
  show_description: true # show blog description in home page
  lowercase_titles: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jektex

include:
  - _pages
  
jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]

